name = "muyu-spa"
main = "worker.js"
compatibility_date = "2026-09-02"

[assets]
directory = "./public"
binding = "ASSETS"
not_found_handling = "single-page-application"

[[kv_namespaces]]
binding = "MUYU_KV"
id = "REPLACE_WITH_KV_NAMESPACE_ID"
