name = "muyu-spa"
main = "worker.js"
compatibility_date = "2026-09-02"

[assets]
directory = "./public"
binding = "ASSETS"
not_found_handling = "single-page-application"

[[kv_namespaces]]
binding = "MUYU_KV"
id = "23f884fa2c6445acbdd808bafb186617"

[triggers]
crons = ["0 * * * *"]
